# This is a basic workflow to help you get started with Actions

name: CI Releases

# Controls when the workflow will run
on:
  push:
    tags:
     - '*' # Push events to every tag

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

    - uses: oprypin/find-latest-tag@v1
     with:
       repository: Gutter-Guys/Gutter_Rat/ # The repository to scan.
       releases-only: false  # We know that all relevant tags have a GitHub release for them.
     id: GR  # The step ID to refer to later.

    - run: echo "Octokit is at version ${{ steps.GR.outputs.tag }}"

    - uses: actions/checkout@v3
      with:
        ref: ${{ steps.GR.outputs.tag }}
        
    - name: GR9 zip
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'GR9.zip'
        path: ./GR9/STLs/*
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: GR9 zip
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'GR6.zip'
        path: ./GR6/STLs/*
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
    - name: Upload GR6 / 9 Release
      uses: ncipollo/release-action@v1
      with:
        bodyFile: "release.md"
        artifacts: 'GR6.zip,GR9.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
